#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-aruba
Version  : 0.14.2
Release  : 9
URL      : https://rubygems.org/downloads/aruba-0.14.2.gem
Source0  : https://rubygems.org/downloads/aruba-0.14.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC-BY-2.5 MIT
Requires: rubygem-aruba-bin
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-cucumber
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-docile
BuildRequires : rubygem-ffi
BuildRequires : rubygem-fuubar
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-ruby-progressbar
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-simplecov-html

%description
[![Gem Version](https://badge.fury.io/rb/aruba.svg)](http://badge.fury.io/rb/aruba)
[![Dependency Status](https://gemnasium.com/cucumber/aruba.svg)](https://gemnasium.com/cucumber/aruba)
[![Code Climate](https://codeclimate.com/github/cucumber/aruba.svg)](https://codeclimate.com/github/cucumber/aruba)
[![Join the chat at https://gitter.im/cucumber/aruba](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/cucumber/aruba?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

%package bin
Summary: bin components for the rubygem-aruba package.
Group: Binaries

%description bin
bin components for the rubygem-aruba package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n aruba-0.14.2
gem spec %{SOURCE0} -l --ruby > rubygem-aruba.gemspec

%build
export LANG=C
gem build rubygem-aruba.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
aruba-0.14.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/aruba-0.14.2
rspec -I.:lib spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/aruba-0.14.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/.document
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/.rubocop.yml
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/.simplecov
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/History.md
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/README.md
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/TODO.md
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/appveyor.yml
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/aruba.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/bin/aruba
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/config/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/.last_run.json
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/.resultset.json
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/.resultset.json.lock
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/application.css
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/application.js
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/colorbox/border.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/colorbox/controls.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/colorbox/loading.gif
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/colorbox/loading_background.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/favicon_green.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/favicon_red.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/favicon_yellow.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/loading.gif
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/magnify.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/smoothness/images/ui-bg_flat_0_aaaaaa_40x100.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/smoothness/images/ui-bg_flat_75_ffffff_40x100.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_55_fbf9ee_1x400.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_65_ffffff_1x400.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_75_dadada_1x400.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_75_e6e6e6_1x400.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_95_fef1ec_1x400.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/smoothness/images/ui-bg_highlight-soft_75_cccccc_1x100.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/smoothness/images/ui-icons_222222_256x240.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/smoothness/images/ui-icons_2e83ff_256x240.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/smoothness/images/ui-icons_454545_256x240.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/smoothness/images/ui-icons_888888_256x240.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/assets/0.10.0/smoothness/images/ui-icons_cd0a0a_256x240.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/coverage/index.html
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/cucumber.yml
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/doc/dependency_decisions.yml
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/.nav
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/command/find_command.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/command/last_command_started.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/command/last_command_stopped.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/command/run.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/command/run_simple.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/command/send_signal.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/command/stderr.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/command/stdout.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/command/stop.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/command/stop_all_commands.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/command/terminate_all_commands.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/command/which.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/core/expand_path.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/environment/append_environment_variable.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/environment/delete_environment_variable.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/environment/prepend_environment_variable.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/environment/set_environment_variable.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/filesystem/cd.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/filesystem/create_directory.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/filesystem/disk_usage.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/filesystem/does_exist.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/filesystem/fixtures.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/filesystem/is_absolute.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/filesystem/is_directory.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/filesystem/is_file.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/filesystem/is_relative.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/filesystem/move.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/text/extract_text.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/text/replace_variables.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/text/sanitize_text.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/api/text/unescape_text.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/cli/console.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/cli/init.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/configuration/activate_announcer_on_command_failure.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/configuration/command_runtime_environment.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/configuration/console_history_file.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/configuration/exit_timeout.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/configuration/fixtures_directories.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/configuration/fixtures_path_prefix.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/configuration/home_directory.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/configuration/io_timeout.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/configuration/keep_ansi.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/configuration/log_level.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/configuration/physical_block_size.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/configuration/remove_ansi_escape_sequences.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/configuration/root_directory.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/configuration/startup_wait_time.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/configuration/usage.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/configuration/working_directory.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/development/build.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/development/test.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/getting_started/cleanup.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/getting_started/install.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/getting_started/run_commands.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/getting_started/supported_testing_frameworks.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/getting_started/writing_good_feature_tests.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/hooks/after/command.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/hooks/before/command.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/matchers/collection/include_an_object.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/matchers/directory/have_sub_directory.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/matchers/file/be_a_command_found_in_path.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/matchers/file/be_existing_executable.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/matchers/file/be_existing_file.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/matchers/file/have_file_content.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/matchers/file/have_file_size.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/matchers/path/be_an_absolute_path.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/matchers/path/be_an_existing_path.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/matchers/path/have_permissions.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/matchers/timeouts.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/platforms/jruby.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/rspec/integration.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/step_definitions/aruba_dev_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/step_definitions/hooks.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/command/debug.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/command/exit_statuses.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/command/in_process.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/command/interactive.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/command/output.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/command/run.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/command/send_signal.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/command/shell.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/command/stderr.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/command/stdout.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/command/stop.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/core/announce.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/environment/append_environment_variable.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/environment/home_variable.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/environment/prepend_environment_variable.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/environment/set_environment_variable.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/append_to_file.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/cd_to_directory.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/check_file_content.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/check_permissions_of_file.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/compare_files.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/copy.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/create_directory.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/create_file.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/existence_of_directory.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/existence_of_file.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/file_content.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/fixtures.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/move.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/non_existence_of_directory.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/non_existence_of_file.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/overwrite_file.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/remove_directory.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/remove_file.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/filesystem/use_fixture.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/steps/overview.feature
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/support/aruba.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/support/jruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/features/support/simplecov_setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/cli-app/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/cli-app/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/cli-app/README.md
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/cli-app/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/cli-app/bin/cli
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/cli-app/cli-app.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/cli-app/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/cli-app/lib/cli/app.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/cli-app/lib/cli/app/suppress_simple_cov_output.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/cli-app/lib/cli/app/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/cli-app/script/console
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/cli-app/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/cli-app/spec/support/aruba.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/copy/file.txt
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/empty-app/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/empty-app/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/empty-app/README.md
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/empty-app/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/empty-app/cli-app.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/empty-app/lib/cli/app.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/empty-app/lib/cli/app/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/getting-started-app/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/getting-started-app/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/getting-started-app/README.md
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/getting-started-app/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/fixtures/spawn_process/stderr.sh
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/api.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/api/command.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/api/core.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/api/deprecated.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/api/environment.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/api/filesystem.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/api/rvm.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/api/text.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/aruba_path.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/basic_configuration.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/basic_configuration/option.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/cli.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/colorizer.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/command.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/config.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/config/jruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/config_wrapper.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/console.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/console/help.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/contracts/absolute_path.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/contracts/enum.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/contracts/is_power_of_two.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/contracts/relative_path.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/cucumber.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/cucumber/command.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/cucumber/core.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/cucumber/environment.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/cucumber/file.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/cucumber/hooks.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/cucumber/rvm.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/cucumber/testing_frameworks.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/event_bus.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/event_bus/name_resolver.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/events.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/extensions/string/strip.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/file_size.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/generators/script_file.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/hooks.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/in_config_wrapper.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/in_process.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/initializer.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/jruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/base/base_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/base/object_formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/collection.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/collection/all.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/collection/include_an_object.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/command.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/command/be_successfully_executed.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/command/have_exit_status.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/command/have_finished_in_time.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/command/have_output.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/command/have_output_on_stderr.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/command/have_output_on_stdout.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/command/have_output_size.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/directory.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/directory/be_an_existing_directory.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/directory/have_sub_directory.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/environment.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/file.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/file/be_a_command_found_in_path.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/file/be_an_existing_executable.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/file/be_an_existing_file.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/file/have_file_content.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/file/have_file_size.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/file/have_same_file_content.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/path.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/path/a_path_matching_pattern.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/path/be_an_absolute_path.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/path/be_an_existing_path.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/path/have_permissions.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/path/match_path_pattern.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/rspec_matcher_include_regexp.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/string.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/string/include_output_string.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/string/match_output_string.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/matchers/string/output_string_eq.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platform.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/announcer.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/aruba_file_creator.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/aruba_fixed_size_file_creator.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/aruba_logger.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/command_monitor.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/determine_disk_usage.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/determine_file_size.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/disk_usage_calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/filesystem_status.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/local_environment.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/simple_table.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/unix_command_string.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/unix_environment_variables.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/unix_platform.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/unix_which.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/windows_command_string.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/windows_environment_variables.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/windows_platform.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/windows_which.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/processes/basic_process.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/processes/debug_process.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/processes/in_process.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/processes/spawn_process.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/reporting.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/runtime.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/spawn_process.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/script/bootstrap
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/script/console
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/script/test
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/api/environment/restore_env_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/api/environment/set_env_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/api/filesystem/file_size_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/api/runtime_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/api_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/aruba_path_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/basic_configuration_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/configuration_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/hooks_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/in_config_wrapper_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/jruby_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/matchers/command/have_output_size_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/matchers/command_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/matchers/directory_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/matchers/file_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/matchers/path_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/platform/simple_table_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/platform/windows_environment_variables_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/rspec_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/runtime_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/aruba/spawn_process_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/event_bus/name_resolver_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/event_bus_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/support/configs/.keep
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/support/configs/aruba.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/support/configs/pry.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/support/configs/rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/support/helpers/.keep
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/support/helpers/reporting.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/support/matchers/.keep
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/support/matchers/option.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/support/shared_contexts/.keep
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/support/shared_contexts/aruba.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/support/shared_examples/.keep
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/support/shared_examples/configuration.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/support/shared_examples/directory.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/spec/support/shared_examples/file.rb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/templates/css/console.css
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/templates/css/filesystem.css
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/templates/css/pygments-autumn.css
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/templates/files.erb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/templates/images/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/templates/images/folder.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/templates/images/page_white.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/templates/images/page_white_gherkin.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/templates/images/page_white_ruby.png
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/templates/index.erb
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/templates/js/filesystem.js
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/templates/js/jquery-1.11.3.min.js
/usr/lib64/ruby/gems/2.3.0/gems/aruba-0.14.2/templates/main.erb
/usr/lib64/ruby/gems/2.3.0/specifications/aruba-0.14.2.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/aruba
